apiVersion: apps/v1
kind: Deployment
metadata: { name: chat-backend }
spec:
  replicas: 2
  selector: { matchLabels: { app: chat-backend } }
  template:
    metadata: { labels: { app: chat-backend } }
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.backend }}
        ports: [ { containerPort: 8080 } ]
        env:
        - { name: OTEL_EXPORTER_OTLP_ENDPOINT, value: "http://otel-collector:4317" }
---
apiVersion: v1
kind: Service
metadata: { name: chat-backend }
spec:
  selector: { app: chat-backend }
  ports: [ { port: 80, targetPort: 8080 } ]
