services:
  postgres:
    image: postgres:16-alpine
    environment: { POSTGRES_DB: chatdb, POSTGRES_USER: chat, POSTGRES_PASSWORD: chatpw }
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.12
    command: ["redpanda","start","--overprovisioned","--smp","1","--memory","1G","--reserve-memory=0M","--check=false"]
    ports: ["9092:9092","9644:9644"]

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Strong.Pass-123
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200","9600:9600"]

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
      - "OPENSEARCH_SECURITY_ENABLED=true"
    ports: ["5601:5601"]
    depends_on: [opensearch]

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]

  otelcol:
    image: otel/opentelemetry-collector:0.112.0
    volumes: [ "./otel-collector.yaml:/etc/otelcol/config.yaml" ]
    command: ["--config=/etc/otelcol/config.yaml"]
    ports: ["4317:4317"]

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment: { COLLECTOR_OTLP_ENABLED: "true" }
    ports: ["16686:16686"]

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes: [ "./prometheus.yml:/etc/prometheus/prometheus.yml" ]
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.1.3
    ports: ["3001:3000"]
    depends_on: [prometheus]