server:
  port: 9094

spring:
#  main:
#    lazy-initialization: true
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${JDBC_USER:chat}
    password: ${JDBC_PASSWORD:chatpw}
  jpa:
    hibernate.ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

management:
  endpoints.web.exposure.include: health,info,prometheus
  metrics.tags.env: ${ENV:local}

jwt:
  issuer: chatstack-prod
  access-token-ttl-min: 15
  refresh-token-ttl-days: 14
  secret: ${JWT_SECRET:dev-secret-change-me}

cookie:
  secure: ${COOKIE_SECURE:false}
  samesite: ${COOKIE_SAMESITE:Lax}
  domain: ${COOKIE_DOMAIN:}

opensearch:
  url: ${OPENSEARCH_URL:http://localhost:9200}
  index: ${OPENSEARCH_INDEX:chat-messages}

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  region: ${S3_REGION:us-east-1}
  bucket: ${S3_BUCKET:chat-attachments}
  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin}
  path-style: ${S3_PATH_STYLE:true}

idempotency:
  ttl-sec: ${IDEMP_TTL_SEC:120}

retention:
  days: ${MESSAGE_RETENTION_DAYS:90}

otel:
  exporter: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

sentry:
  dsn: ${SENTRY_DSN:}
